// Generated by CoffeeScript 1.4.0

define(['angular'], function(angular) {
  'use strict';
  angular.module('AngularRequire', []);
  angular.element(document).ready(function() {
    angular.bootstrap(document, ["AngularRequire"]);
    console.log("hi-app");
  });
});
